
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
dotenv.config({ path: '.env.local' });
dotenv.config(); // Also load .env as fallback

import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("POSTGRES_PRISMA_URL") || env("DATABASE_URL"),
    directUrl: env("POSTGRES_URL_NON_POOLING"),
  },
});
